services:
  chat-db:
    container_name: chat-db
    image: postgres:14.6
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - .:/docker-entrypoint-initdb.d

 # web:
 #   container_name: fastapi
 # build:
 #   context: .
 #   ports:
 #     - "8000:8000"
 #   expose:
 #     - 8000
 #   volumes:
 #     - .:/app
 #   depends_on:
 #     - user-db